"""Built-in style profiles."""

from __future__ import annotations

from datetime import datetime, timezone

from .style_schema import (
    ChartStyle,
    ColourPalette,
    DiagramStyle,
    RendererStyleHints,
    StyleMetadata,
    StyleProfile,
    TypographyStyle,
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _style(
    style_id: str,
    style_name: str,
    description: str,
    tags: list[str],
    *,
    sequence: list[str],
    primary: str | None = None,
    secondary: str | None = None,
    accent: str | None = None,
    neutral: str = "#888888",
    background: str = "#ffffff",
    plot_background: str | None = None,
    grid: str = "light",
    legend_position: str = "right",
    title_alignment: str = "left",
    dark: bool = False,
    node_fill: str | None = None,
    node_stroke: str | None = None,
    decision_fill: str | None = None,
    edge_colour: str | None = None,
    font_family: str = "Arial",
    font_weight: str = "normal",
    title_size: int = 18,
    label_size: int = 12,
    tick_size: int = 10,
    bar_gap: float | None = None,
    line_shape: str = "linear",
    border_radius: int = 5,
    stroke_width: int = 1,
) -> StyleProfile:
    """Build a chart+diagram style profile from a colour sequence.

    Diagram colours and renderer hints are derived from the palette so that a
    new theme only needs to specify its distinctive colours.
    """
    primary = primary or sequence[0]
    secondary = secondary or (sequence[1] if len(sequence) > 1 else primary)
    accent = accent or (sequence[2] if len(sequence) > 2 else secondary)
    plot_background = plot_background or background
    node_stroke = node_stroke or primary
    node_fill = node_fill or (primary if dark else "#eeeeee")
    decision_fill = decision_fill or accent
    edge_colour = edge_colour or node_stroke
    return StyleProfile(
        metadata=StyleMetadata(
            style_id=style_id,
            style_name=style_name,
            description=description,
            created_at=_now(),
            tags=tags,
        ),
        palette=ColourPalette(
            primary=primary,
            secondary=secondary,
            accent=accent,
            neutral=neutral,
            sequence=sequence,
        ),
        typography=TypographyStyle(
            font_family=font_family,
            font_weight=font_weight,
            title_size=title_size,
            label_size=label_size,
            tick_size=tick_size,
        ),
        chart=ChartStyle(
            background=background,
            plot_background=plot_background,
            grid=grid,
            legend_position=legend_position,
            label_density="medium",
            title_alignment=title_alignment,
            bar_gap=bar_gap,
            line_shape=line_shape,
        ),
        diagram=DiagramStyle(
            direction="TD",
            node_fill=node_fill,
            node_stroke=node_stroke,
            decision_fill=decision_fill,
            edge_colour=edge_colour,
            border_radius=border_radius,
            stroke_width=stroke_width,
        ),
        renderer_hints=RendererStyleHints(
            plotly_template="plotly_dark" if dark else "plotly_white",
            mermaid_theme="dark" if dark else "base",
        ),
        supported_visual_kinds=["chart", "diagram"],
        supported_renderers=["plotly", "mermaid"],
    )


def _additional_style_profiles() -> list[StyleProfile]:
    """Standard colour schemes available out of the box."""
    return [
        # --- dark themes ---
        _style(
            "dark_slate",
            "Dark Slate",
            "Dark slate background with cool blue-teal accents.",
            ["dark", "cool", "presentation"],
            background="#1e293b",
            grid="none",
            dark=True,
            neutral="#94a3b8",
            sequence=["#38bdf8", "#34d399", "#fbbf24", "#f472b6", "#a78bfa", "#fb7185"],
            border_radius=6,
            stroke_width=1,
        ),
        _style(
            "midnight_neon",
            "Midnight Neon",
            "Near-black background with vivid neon data colours.",
            ["dark", "neon", "vibrant"],
            background="#0d1829",
            grid="none",
            dark=True,
            neutral="#64748b",
            sequence=["#ff6d00", "#00e5ff", "#00e676", "#d500f9", "#ffea00", "#ff1744"],
            font_weight="bold",
            border_radius=0,
            stroke_width=2,
            line_shape="linear",
        ),
        # --- vibrant / categorical ---
        _style(
            "vibrant",
            "Vibrant",
            "Bright, high-saturation categorical palette on white.",
            ["vibrant", "categorical", "bright"],
            sequence=["#e6194b", "#3cb44b", "#4363d8", "#f58231", "#911eb4", "#42d4f4"],
            font_weight="bold",
            border_radius=4,
            bar_gap=0.3,
        ),
        _style(
            "colorblind_safe",
            "Colorblind Safe",
            "Okabe-Ito colour-vision-deficiency-safe palette.",
            ["accessible", "colorblind", "categorical"],
            primary="#0072b2",
            sequence=["#0072b2", "#e69f00", "#009e73", "#cc79a7", "#56b4e9", "#d55e00"],
            border_radius=4,
            stroke_width=2,
        ),
        # --- sequential / single-hue ---
        _style(
            "ocean",
            "Ocean",
            "Sequential ocean blues and teals.",
            ["sequential", "blue", "cool"],
            grid="light",
            sequence=["#023e8a", "#0077b6", "#0096c7", "#00b4d8", "#48cae4", "#90e0ef"],
            line_shape="spline",
            border_radius=6,
        ),
        _style(
            "sunset",
            "Sunset",
            "Warm sunset reds, oranges and magentas.",
            ["warm", "sunset", "categorical"],
            sequence=["#ff0054", "#ff5400", "#ff8500", "#ff9e00", "#9e0059", "#390099"],
            line_shape="spline",
            border_radius=8,
        ),
        _style(
            "forest",
            "Forest",
            "Earthy greens for natural, organic themes.",
            ["green", "earth", "natural"],
            sequence=["#283618", "#606c38", "#588157", "#3a5a40", "#a3b18a", "#dad7cd"],
            border_radius=6,
            line_shape="spline",
        ),
        _style(
            "pastel",
            "Pastel",
            "Soft pastel palette for gentle, approachable visuals.",
            ["pastel", "soft", "light"],
            neutral="#cccccc",
            sequence=["#ffadad", "#ffd6a5", "#caffbf", "#9bf6ff", "#bdb2ff", "#fdffb6"],
            border_radius=12,
            stroke_width=1,
            bar_gap=0.35,
        ),
        _style(
            "monochrome_blue",
            "Monochrome Blue",
            "Single-hue sequential blues for ordered data.",
            ["monochrome", "sequential", "blue"],
            sequence=["#08306b", "#2171b5", "#4292c6", "#6baed6", "#9ecae1", "#c6dbef"],
            border_radius=3,
        ),
        # --- accessible / print ---
        _style(
            "high_contrast",
            "High Contrast",
            "Bold high-contrast palette for accessibility and print.",
            ["accessible", "high-contrast", "bold"],
            grid="medium",
            neutral="#555555",
            sequence=["#000000", "#e6194b", "#3cb44b", "#4363d8", "#f58231", "#ffe119"],
            font_weight="bold",
            border_radius=0,
            stroke_width=3,
            title_size=20,
            label_size=13,
            tick_size=11,
        ),
        _style(
            "print_friendly",
            "Print Friendly",
            "Greyscale-first palette optimised for black-and-white printing.",
            ["accessible", "print", "monochrome"],
            background="#ffffff",
            plot_background="#ffffff",
            neutral="#888888",
            grid="medium",
            sequence=["#000000", "#333333", "#555555", "#777777", "#999999", "#bbbbbb"],
            font_weight="bold",
            border_radius=0,
            stroke_width=2,
            title_size=20,
        ),
        # --- developer / technical ---
        _style(
            "solarized",
            "Solarized",
            "Solarized accent palette on a warm cream background.",
            ["solarized", "muted", "developer"],
            background="#fdf6e3",
            plot_background="#fdf6e3",
            neutral="#93a1a1",
            sequence=["#268bd2", "#2aa198", "#859900", "#b58900", "#cb4b16", "#d33682"],
            font_family="monospace",
            border_radius=3,
            stroke_width=1,
        ),
        _style(
            "data_science",
            "Data Science",
            "Dark notebook-inspired theme — the palette favoured by Matplotlib's dark background.",
            ["dark", "technical", "data"],
            background="#1c1c2e",
            plot_background="#1c1c2e",
            dark=True,
            neutral="#5c6370",
            sequence=["#61afef", "#e06c75", "#98c379", "#e5c07b", "#c678dd", "#56b6c2"],
            font_family="monospace",
            border_radius=0,
            stroke_width=1,
        ),
        # --- earth / organic ---
        _style(
            "warm_earth",
            "Warm Earth",
            "Muted autumnal earth tones.",
            ["earth", "autumn", "muted"],
            neutral="#b6ad90",
            sequence=["#582f0e", "#7f4f24", "#936639", "#a68a64", "#b6ad90", "#c2c5aa"],
            border_radius=6,
            line_shape="spline",
        ),
        _style(
            "terra_cotta",
            "Terra Cotta",
            "Warm clay and terracotta tones with dusty sage accents.",
            ["earth", "warm", "natural"],
            background="#fdf4ef",
            plot_background="#fdf4ef",
            neutral="#b89b8a",
            sequence=["#c1440e", "#d9622b", "#e07b54", "#e8a87c", "#7d9b76", "#a8c5a0"],
            border_radius=8,
            line_shape="spline",
        ),
        _style(
            "matcha",
            "Matcha",
            "Japanese-inspired greens with warm cream and ink tones.",
            ["green", "zen", "natural"],
            background="#f7f5e8",
            plot_background="#f7f5e8",
            neutral="#a0a870",
            sequence=["#2d4a1e", "#4a7c35", "#6fa84e", "#9ec97a", "#c5e0a8", "#e5f0d0"],
            font_family="Georgia",
            border_radius=12,
            stroke_width=1,
            line_shape="spline",
        ),
        _style(
            "autumn",
            "Autumn",
            "Rich fall colours — deep reds, burnt oranges and golds.",
            ["warm", "seasonal", "earth"],
            background="#fdf8f0",
            plot_background="#fdf8f0",
            neutral="#c4855a",
            sequence=["#8b1a1a", "#c0392b", "#d35400", "#e67e22", "#f39c12", "#8e6914"],
            font_family="Georgia",
            border_radius=6,
            line_shape="spline",
        ),
        # --- cool / minimal ---
        _style(
            "nordic",
            "Nordic",
            "Scandinavian minimalist palette — cool greys, slate and ice blue.",
            ["minimal", "cool", "professional"],
            background="#f5f7fa",
            plot_background="#ffffff",
            neutral="#8896a5",
            sequence=["#2d3e50", "#4a6fa5", "#6b98d4", "#a8c4e0", "#d4e5f4", "#e8f1f8"],
            border_radius=2,
            stroke_width=1,
            bar_gap=0.4,
        ),
        _style(
            "arctic",
            "Arctic",
            "Crisp ice blues and frost whites for clean, cold aesthetics.",
            ["cool", "minimal", "blue"],
            background="#f0f8ff",
            plot_background="#f0f8ff",
            neutral="#90b8d0",
            sequence=["#1e3a5f", "#2e6da4", "#5ba3d0", "#8ec8e8", "#b8e0f4", "#dff0fa"],
            border_radius=4,
            stroke_width=1,
            line_shape="spline",
        ),
        # --- elegant / professional ---
        _style(
            "rose_gold",
            "Rose Gold",
            "Elegant rose-gold tones for polished presentations.",
            ["elegant", "warm", "pink"],
            background="#fff8f6",
            plot_background="#fff8f6",
            neutral="#c9a09a",
            sequence=["#b5446e", "#d4697a", "#e8918a", "#f0b8a8", "#f7d4c4", "#fde8de"],
            font_family="Georgia",
            border_radius=10,
            stroke_width=1,
            line_shape="spline",
        ),
        _style(
            "executive",
            "Executive",
            "Dark charcoal and navy with gold accents — boardroom ready.",
            ["dark", "corporate", "elegant"],
            background="#1a1f2e",
            plot_background="#1a1f2e",
            dark=True,
            neutral="#6b7280",
            sequence=["#c9a227", "#e8c547", "#4a90d9", "#6baed6", "#a0b8d0", "#d0dde8"],
            font_family="Georgia",
            font_weight="bold",
            title_size=20,
            border_radius=3,
            stroke_width=1,
        ),
        _style(
            "lavender_mist",
            "Lavender Mist",
            "Soft violet and lilac palette with warm undertones.",
            ["pastel", "purple", "soft"],
            background="#faf8ff",
            plot_background="#faf8ff",
            neutral="#b8a8cc",
            sequence=["#6b3fa0", "#9b59b6", "#bb8fce", "#d7bde2", "#e8daef", "#f5eef8"],
            border_radius=12,
            stroke_width=1,
            line_shape="spline",
        ),
        # --- bold / vibrant ---
        _style(
            "berry",
            "Berry",
            "Jewel-toned berry and plum palette for rich, bold visuals.",
            ["vibrant", "purple", "bold"],
            background="#fdf4ff",
            plot_background="#fdf4ff",
            neutral="#a855a0",
            sequence=["#6d1a5e", "#9c2787", "#c0399e", "#e05aaa", "#7b2d8b", "#4a1a6b"],
            font_weight="bold",
            border_radius=6,
            stroke_width=2,
        ),
        _style(
            "candy",
            "Candy",
            "Bright, playful candy-pop colours on white.",
            ["vibrant", "playful", "bright"],
            neutral="#dd88bb",
            sequence=["#ff6b9d", "#ff9a3c", "#ffcc02", "#4ecdc4", "#45b7d1", "#a78bfa"],
            font_weight="bold",
            border_radius=16,
            stroke_width=1,
            bar_gap=0.3,
            line_shape="spline",
        ),
        _style(
            "teal_coral",
            "Teal & Coral",
            "Contemporary teal and coral contrast palette.",
            ["vibrant", "modern", "categorical"],
            neutral="#94a3b8",
            sequence=["#008080", "#20b2aa", "#40e0d0", "#ff6b6b", "#ff8e53", "#ffd166"],
            border_radius=6,
            bar_gap=0.3,
        ),
        # --- dark / sci-fi ---
        _style(
            "cyberpunk",
            "Cyberpunk",
            "Vivid neon green and magenta on deep purple-black.",
            ["dark", "neon", "vibrant", "tech"],
            background="#0a0014",
            plot_background="#0a0014",
            dark=True,
            neutral="#6b4f8a",
            sequence=["#39ff14", "#ff2d78", "#00f5ff", "#fffc00", "#bf5af2", "#ff6b35"],
            font_weight="bold",
            border_radius=0,
            stroke_width=2,
            line_shape="linear",
        ),
        _style(
            "deep_space",
            "Deep Space",
            "Dark indigo background with stellar purple and cyan highlights.",
            ["dark", "space", "cool"],
            background="#090b1a",
            plot_background="#090b1a",
            dark=True,
            neutral="#4a4e8a",
            sequence=["#a78bfa", "#60a5fa", "#34d399", "#fb923c", "#f472b6", "#facc15"],
            border_radius=6,
            stroke_width=1,
            line_shape="spline",
        ),
        # --- vintage ---
        _style(
            "retro",
            "Retro",
            "1970s-inspired warm amber, avocado green and harvest gold.",
            ["retro", "warm", "vintage"],
            background="#fef3c7",
            plot_background="#fffbeb",
            neutral="#92400e",
            sequence=["#b45309", "#d97706", "#65a30d", "#854d0e", "#a16207", "#4d7c0f"],
            font_family="Georgia",
            font_weight="bold",
            title_size=20,
            border_radius=8,
            bar_gap=0.25,
            line_shape="spline",
        ),
    ]


def list_builtin_style_profiles() -> list[StyleProfile]:
    return [
        StyleProfile(
            metadata=StyleMetadata(
                style_id="corporate_blue",
                style_name="Corporate Blue",
                description="Clean corporate style with blue accents.",
                created_at=_now(),
                tags=["corporate", "blue", "presentation"],
            ),
            palette=ColourPalette(
                primary="#1f4e79",
                secondary="#5b9bd5",
                accent="#70ad47",
                neutral="#a5a5a5",
                warning="#ffc000",
                success="#70ad47",
                danger="#c00000",
                sequence=["#1f4e79", "#5b9bd5", "#70ad47", "#a5a5a5"],
            ),
            typography=TypographyStyle(font_family="Arial", title_size=18, label_size=12, tick_size=10),
            chart=ChartStyle(
                background="#ffffff",
                plot_background="#ffffff",
                grid="light",
                legend_position="right",
                label_density="medium",
                title_alignment="left",
            ),
            diagram=DiagramStyle(
                direction="TD",
                node_fill="#d9eaf7",
                node_stroke="#1f4e79",
                decision_fill="#fff2cc",
                edge_colour="#1f4e79",
            ),
            renderer_hints=RendererStyleHints(plotly_template="plotly_white", mermaid_theme="base"),
            supported_visual_kinds=["chart", "diagram"],
            supported_renderers=["plotly", "mermaid"],
        ),
        StyleProfile(
            metadata=StyleMetadata(
                style_id="minimal_grey",
                style_name="Minimal Grey",
                description="Neutral low-colour styling.",
                created_at=_now(),
                tags=["minimal", "grey"],
            ),
            palette=ColourPalette(
                primary="#666666",
                secondary="#999999",
                accent="#444444",
                neutral="#d9d9d9",
                sequence=["#666666", "#999999", "#bbbbbb", "#dddddd"],
            ),
            typography=TypographyStyle(font_family="Arial", title_size=16, label_size=11, tick_size=10),
            chart=ChartStyle(
                background="#f7f7f7",
                plot_background="#ffffff",
                grid="light",
                legend_position="right",
                label_density="medium",
                title_alignment="left",
            ),
            diagram=DiagramStyle(
                direction="TD",
                node_fill="#eeeeee",
                node_stroke="#666666",
                decision_fill="#f5f5f5",
                edge_colour="#666666",
            ),
            renderer_hints=RendererStyleHints(plotly_template="plotly_white", mermaid_theme="base"),
            supported_visual_kinds=["chart", "diagram"],
            supported_renderers=["plotly", "mermaid", "chartjs"],
        ),
        StyleProfile(
            metadata=StyleMetadata(
                style_id="presentation_green",
                style_name="Presentation Green",
                description="Presentation-friendly green highlights.",
                created_at=_now(),
                tags=["presentation", "green"],
            ),
            palette=ColourPalette(
                primary="#2f7d32",
                secondary="#81c784",
                accent="#66bb6a",
                neutral="#bdbdbd",
                sequence=["#2f7d32", "#66bb6a", "#a5d6a7", "#c8e6c9"],
            ),
            typography=TypographyStyle(font_family="Arial", title_size=18, label_size=12, tick_size=10),
            chart=ChartStyle(
                background="#ffffff",
                plot_background="#ffffff",
                grid="light",
                legend_position="bottom",
                label_density="medium",
                title_alignment="left",
            ),
            diagram=DiagramStyle(
                direction="TD",
                node_fill="#e8f5e9",
                node_stroke="#2f7d32",
                decision_fill="#fffde7",
                edge_colour="#2f7d32",
            ),
            renderer_hints=RendererStyleHints(plotly_template="plotly_white", mermaid_theme="base"),
            supported_visual_kinds=["chart", "diagram"],
            supported_renderers=["plotly", "mermaid"],
        ),
        StyleProfile(
            metadata=StyleMetadata(
                style_id="process_blue",
                style_name="Process Blue",
                description="Flowchart and process diagram styling.",
                created_at=_now(),
                tags=["diagram", "process", "blue"],
            ),
            palette=ColourPalette(
                primary="#1f4e79",
                secondary="#5b9bd5",
                accent="#70ad47",
                sequence=["#d9eaf7", "#fff2cc", "#e2f0d9"],
            ),
            typography=TypographyStyle(font_family="Arial", title_size=16, label_size=11, tick_size=10),
            chart=ChartStyle(
                background="#ffffff",
                plot_background="#ffffff",
                grid="none",
                legend_position="none",
                label_density="low",
                title_alignment="left",
            ),
            diagram=DiagramStyle(
                direction="TD",
                node_fill="#d9eaf7",
                node_stroke="#1f4e79",
                decision_fill="#fff2cc",
                edge_colour="#1f4e79",
                class_defs={
                    "process": {
                        "fill": "#d9eaf7",
                        "stroke": "#1f4e79",
                        "color": "#000000",
                    },
                    "decision": {
                        "fill": "#fff2cc",
                        "stroke": "#1f4e79",
                        "color": "#000000",
                    },
                    "start": {
                        "fill": "#e2f0d9",
                        "stroke": "#1f4e79",
                        "color": "#000000",
                    },
                    "end": {
                        "fill": "#fce4d6",
                        "stroke": "#1f4e79",
                        "color": "#000000",
                    },
                },
            ),
            renderer_hints=RendererStyleHints(plotly_template="plotly_white", mermaid_theme="base"),
            supported_visual_kinds=["diagram", "chart"],
            supported_renderers=["mermaid", "plotly"],
        ),
        *_additional_style_profiles(),
    ]
