"""Built-in composite style profiles.

Each built-in style is a complete design system: a colour palette, a
typographic identity (font family, weight, and title/label/tick sizes), and a
chart surface treatment (background, plot background, grid, legend position,
title alignment, bar gap, line shape). The styles are intentionally more than
colour schemes so that switching a style changes the whole feel of a chart or
diagram, not just its data colours.
"""

from __future__ import annotations

from datetime import datetime, timezone

from .style_schema import (
    ChartStyle,
    ColourPalette,
    DiagramStyle,
    RendererStyleHints,
    StyleMetadata,
    StyleProfile,
    TypographyStyle,
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _style(
    style_id: str,
    style_name: str,
    description: str,
    tags: list[str],
    *,
    sequence: list[str],
    primary: str | None = None,
    secondary: str | None = None,
    accent: str | None = None,
    neutral: str = "#888888",
    background: str = "#ffffff",
    plot_background: str | None = None,
    grid: str = "light",
    legend_position: str = "right",
    label_density: str = "medium",
    title_alignment: str = "left",
    dark: bool = False,
    node_fill: str | None = None,
    node_stroke: str | None = None,
    decision_fill: str | None = None,
    edge_colour: str | None = None,
    font_family: str = "Arial",
    font_weight: str = "normal",
    title_size: int = 18,
    label_size: int = 12,
    tick_size: int = 10,
    bar_gap: float | None = None,
    line_shape: str = "linear",
    border_radius: int = 5,
    stroke_width: int = 1,
    diagram_direction: str = "TD",
    mermaid_theme: str | None = None,
) -> StyleProfile:
    """Build a composite chart+diagram style profile.

    Diagram colours and renderer hints are derived from the palette when not
    given explicitly, so a new theme only needs to specify its distinctive
    colours plus its typographic and surface identity.
    """
    primary = primary or sequence[0]
    secondary = secondary or (sequence[1] if len(sequence) > 1 else primary)
    accent = accent or (sequence[2] if len(sequence) > 2 else secondary)
    plot_background = plot_background or background
    node_stroke = node_stroke or primary
    node_fill = node_fill or (primary if dark else "#eeeeee")
    decision_fill = decision_fill or accent
    edge_colour = edge_colour or node_stroke
    return StyleProfile(
        metadata=StyleMetadata(
            style_id=style_id,
            style_name=style_name,
            description=description,
            created_at=_now(),
            tags=tags,
        ),
        palette=ColourPalette(
            primary=primary,
            secondary=secondary,
            accent=accent,
            neutral=neutral,
            sequence=sequence,
        ),
        typography=TypographyStyle(
            font_family=font_family,
            font_weight=font_weight,
            title_size=title_size,
            label_size=label_size,
            tick_size=tick_size,
        ),
        chart=ChartStyle(
            background=background,
            plot_background=plot_background,
            grid=grid,
            legend_position=legend_position,
            label_density=label_density,
            title_alignment=title_alignment,
            bar_gap=bar_gap,
            line_shape=line_shape,
        ),
        diagram=DiagramStyle(
            direction=diagram_direction,
            node_fill=node_fill,
            node_stroke=node_stroke,
            decision_fill=decision_fill,
            edge_colour=edge_colour,
            border_radius=border_radius,
            stroke_width=stroke_width,
        ),
        renderer_hints=RendererStyleHints(
            plotly_template="plotly_dark" if dark else "plotly_white",
            mermaid_theme=mermaid_theme or ("dark" if dark else "base"),
        ),
        supported_visual_kinds=["chart", "diagram"],
        supported_renderers=["plotly", "mermaid"],
    )


def list_builtin_style_profiles() -> list[StyleProfile]:
    """Composite design-system styles available out of the box."""
    return [
        # --- Editorial / publication ---
        _style(
            "editorial_serif",
            "Editorial Serif",
            "Newspaper-style serif typography on warm cream, with a restrained "
            "charcoal palette and medium grid for data journalism.",
            ["editorial", "serif", "publication"],
            background="#fbf7f0",
            plot_background="#fffdf7",
            grid="medium",
            legend_position="bottom",
            label_density="medium",
            title_alignment="left",
            neutral="#4a4a4a",
            sequence=["#1b1b1b", "#7a1f1f", "#1f4e79", "#5b6b3a", "#9a6a1f", "#6a4c93"],
            font_family="Georgia",
            font_weight="normal",
            title_size=22,
            label_size=13,
            tick_size=11,
            bar_gap=0.2,
            line_shape="linear",
            border_radius=2,
            stroke_width=1,
        ),
        _style(
            "magazine_bold",
            "Magazine Bold",
            "Glossy magazine feel: heavy sans titles, generous spacing, vivid "
            "categorical colours on white with smooth spline lines.",
            ["magazine", "bold", "vibrant"],
            background="#ffffff",
            grid="light",
            legend_position="right",
            label_density="high",
            title_alignment="left",
            sequence=["#e6194b", "#3cb44b", "#4363d8", "#f58231", "#911eb4", "#42d4f4"],
            font_family="Helvetica",
            font_weight="bold",
            title_size=26,
            label_size=14,
            tick_size=12,
            bar_gap=0.3,
            line_shape="spline",
            border_radius=10,
            stroke_width=2,
        ),
        # --- Corporate / executive ---
        _style(
            "boardroom",
            "Boardroom",
            "Executive navy-and-gold on white, Helvetica bold, bottom legend and "
            "a fine grid for boardroom decks.",
            ["corporate", "executive", "presentation"],
            background="#ffffff",
            plot_background="#fafcff",
            grid="light",
            legend_position="bottom",
            label_density="medium",
            title_alignment="left",
            primary="#1f3b66",
            secondary="#5b8def",
            accent="#c9a227",
            neutral="#9aa3b0",
            sequence=["#1f3b66", "#5b8def", "#c9a227", "#3c5a8a", "#8a6d1f", "#b0b8c4"],
            font_family="Helvetica",
            font_weight="bold",
            title_size=20,
            label_size=12,
            tick_size=10,
            bar_gap=0.25,
            line_shape="linear",
            border_radius=4,
            stroke_width=2,
        ),
        _style(
            "minimal_swiss",
            "Minimal Swiss",
            "Flat Swiss design: one accent, lots of whitespace, no grid, tiny ticks "
            "and a clean Helvetica voice.",
            ["minimal", "flat", "swiss"],
            background="#ffffff",
            plot_background="#ffffff",
            grid="none",
            legend_position="none",
            label_density="low",
            title_alignment="left",
            primary="#111111",
            secondary="#d6336c",
            accent="#d6336c",
            neutral="#cccccc",
            sequence=["#d6336c", "#111111", "#888888", "#bbbbbb", "#e0e0e0", "#f5f5f5"],
            font_family="Helvetica",
            font_weight="normal",
            title_size=18,
            label_size=11,
            tick_size=9,
            bar_gap=0.4,
            line_shape="linear",
            border_radius=0,
            stroke_width=1,
        ),
        # --- Technical / engineering ---
        _style(
            "technical_report",
            "Technical Report",
            "Engineering report look: clean sans on white, a fine grid, muted "
            "blue-grey palette and centred titles.",
            ["technical", "engineering", "report"],
            background="#ffffff",
            plot_background="#ffffff",
            grid="light",
            legend_position="right",
            label_density="medium",
            title_alignment="center",
            neutral="#6b7280",
            sequence=["#334155", "#0ea5e9", "#64748b", "#94a3b8", "#cbd5e1", "#1e293b"],
            font_family="Segoe UI",
            font_weight="normal",
            title_size=18,
            label_size=12,
            tick_size=10,
            bar_gap=0.2,
            line_shape="linear",
            border_radius=3,
            stroke_width=1,
        ),
        _style(
            "academic_paper",
            "Academic Paper",
            "Journal-style serif on white, thin grid, black/grey palette and a "
            "bottom legend for dense reference figures.",
            ["academic", "serif", "print"],
            background="#ffffff",
            plot_background="#ffffff",
            grid="light",
            legend_position="bottom",
            label_density="high",
            title_alignment="left",
            neutral="#555555",
            sequence=["#000000", "#444444", "#666666", "#888888", "#aaaaaa", "#cccccc"],
            font_family="Times New Roman",
            font_weight="normal",
            title_size=16,
            label_size=11,
            tick_size=9,
            bar_gap=0.2,
            line_shape="linear",
            border_radius=0,
            stroke_width=1,
        ),
        # --- Dark / dashboard ---
        _style(
            "dashboard_dark",
            "Dashboard Dark",
            "Operations dashboard on dark slate: Segoe UI, bright categorical "
            "data colours and a subtle grid for at-a-glance monitoring.",
            ["dark", "dashboard", "ops"],
            background="#0f172a",
            plot_background="#111c33",
            grid="light",
            legend_position="right",
            label_density="medium",
            title_alignment="left",
            dark=True,
            neutral="#94a3b8",
            sequence=["#38bdf8", "#34d399", "#fbbf24", "#f472b6", "#a78bfa", "#fb7185"],
            font_family="Segoe UI",
            font_weight="normal",
            title_size=18,
            label_size=12,
            tick_size=10,
            bar_gap=0.25,
            line_shape="linear",
            border_radius=6,
            stroke_width=1,
        ),
        _style(
            "terminal_neon",
            "Terminal Neon",
            "Developer/CLI vibe: monospace on near-black, neon green and amber "
            "data colours, no grid and high-contrast titles.",
            ["dark", "developer", "neon"],
            background="#0a0a0a",
            plot_background="#0d0d0d",
            grid="none",
            legend_position="right",
            label_density="low",
            title_alignment="left",
            dark=True,
            neutral="#6b7280",
            sequence=["#00e676", "#ffb300", "#00e5ff", "#d500f9", "#ff1744", "#ffea00"],
            font_family="Courier New",
            font_weight="bold",
            title_size=18,
            label_size=12,
            tick_size=11,
            bar_gap=0.2,
            line_shape="linear",
            border_radius=0,
            stroke_width=2,
        ),
        # --- Soft / friendly ---
        _style(
            "pastel_soft",
            "Pastel Soft",
            "Friendly rounded sans on light, soft pastels, light grid and large "
            "rounded corners for approachable visuals.",
            ["pastel", "soft", "friendly"],
            background="#fffafc",
            plot_background="#ffffff",
            grid="light",
            legend_position="right",
            label_density="medium",
            title_alignment="left",
            neutral="#cccccc",
            sequence=["#ffadad", "#ffd6a5", "#caffbf", "#9bf6ff", "#bdb2ff", "#fdffb6"],
            font_family="Verdana",
            font_weight="normal",
            title_size=18,
            label_size=12,
            tick_size=10,
            bar_gap=0.35,
            line_shape="spline",
            border_radius=12,
            stroke_width=1,
        ),
        _style(
            "marketing_punch",
            "Marketing Punch",
            "Punchy marketing look: heavy bold sans, vivid palette, no grid, big "
            "titles and wide bars for hero charts.",
            ["marketing", "bold", "vibrant"],
            background="#ffffff",
            plot_background="#ffffff",
            grid="none",
            legend_position="bottom",
            label_density="medium",
            title_alignment="left",
            sequence=["#ff0054", "#ff5400", "#ff8500", "#ff9e00", "#9e0059", "#390099"],
            font_family="Helvetica",
            font_weight="bold",
            title_size=28,
            label_size=14,
            tick_size=12,
            bar_gap=0.3,
            line_shape="linear",
            border_radius=14,
            stroke_width=2,
        ),
        # --- Sequential / thematic ---
        _style(
            "ocean_cool",
            "Ocean Cool",
            "Sequential ocean blues on white, clean sans, light grid and smooth "
            "spline lines for trend and area charts.",
            ["sequential", "blue", "cool"],
            background="#ffffff",
            plot_background="#f7fbff",
            grid="light",
            legend_position="right",
            label_density="medium",
            title_alignment="left",
            sequence=["#023e8a", "#0077b6", "#0096c7", "#00b4d8", "#48cae4", "#90e0ef"],
            font_family="Segoe UI",
            font_weight="normal",
            title_size=18,
            label_size=12,
            tick_size=10,
            bar_gap=0.25,
            line_shape="spline",
            border_radius=6,
            stroke_width=1,
        ),
        _style(
            "sunset_warm",
            "Sunset Warm",
            "Warm sunset palette on cream, serif titles and spline lines for "
            "expressive, warm-toned visuals.",
            ["warm", "sunset", "editorial"],
            background="#fff8f0",
            plot_background="#fffdf9",
            grid="light",
            legend_position="right",
            label_density="medium",
            title_alignment="left",
            sequence=["#ff0054", "#ff5400", "#ff8500", "#ff9e00", "#9e0059", "#390099"],
            font_family="Georgia",
            font_weight="normal",
            title_size=20,
            label_size=13,
            tick_size=11,
            bar_gap=0.25,
            line_shape="spline",
            border_radius=8,
            stroke_width=1,
        ),
        # --- Accessible ---
        _style(
            "colorblind_safe",
            "Colorblind Safe",
            "Okabe-Ito colour-vision-deficiency-safe palette on white, clean sans, "
            "medium grid and a bold title for accessible reporting.",
            ["accessible", "colorblind", "categorical"],
            background="#ffffff",
            plot_background="#ffffff",
            grid="medium",
            legend_position="right",
            label_density="medium",
            title_alignment="left",
            primary="#0072b2",
            sequence=["#0072b2", "#e69f00", "#009e73", "#cc79a7", "#56b4e9", "#d55e00"],
            font_family="Arial",
            font_weight="bold",
            title_size=20,
            label_size=13,
            tick_size=11,
            bar_gap=0.25,
            line_shape="linear",
            border_radius=4,
            stroke_width=2,
        ),
        _style(
            "high_contrast_print",
            "High Contrast Print",
            "Bold black-on-white with strong grid and large type for print and "
            "low-vision accessibility.",
            ["accessible", "high-contrast", "print"],
            background="#ffffff",
            plot_background="#ffffff",
            grid="medium",
            legend_position="bottom",
            label_density="low",
            title_alignment="left",
            neutral="#555555",
            sequence=["#000000", "#e6194b", "#3cb44b", "#4363d8", "#f58231", "#ffe119"],
            font_family="Arial",
            font_weight="bold",
            title_size=22,
            label_size=14,
            tick_size=12,
            bar_gap=0.3,
            line_shape="linear",
            border_radius=0,
            stroke_width=3,
        ),
    ]
